### ISSUE TITLE
Add missing validation for string input in mpz

### ISSUE THREAD

**Issue by skirpichev** [diofant/python-gmp#17]
It should reject invalid digits (not in 0-9, a-z or A-Z range, depending on the base value).

**Comment by rruuaanng** [comment]
Why do invalid numbers include `A-Za-z`, shouldn't they be `0-9`? If such a function is needed, I think we can prepare a series of commonly used validation functions, such as determining whether a string is a decimal number, or whether it's a hexadecimal number. And other ....
(You must be wondering why I'm here. I'm interested in it.)

**Comment by skirpichev** [comment]
> Why do invalid numbers include A-Za-z, shouldn't they be 0-9?

Which digits are accepted - depends on the base value, which can be up to 62 (probably, there should be also some global switch to enable strict Python compatibility - int() accepts only bases up to 36).  E.g. if base=10 - we should reject strings with any letters.

**Comment by rruuaanng** [comment]
It seems my understanding is correct. I wrote a function to check if a string is a base-n number (it currently only supports basic base checking, but you can review it). I added a `c_utils.c` file for this, and I think we can move all C-related utilities into it in the future.
