### ISSUE TITLE
Support underscores in mpz for string input

### ISSUE THREAD

**Issue by skirpichev** [diofant/python-gmp#46]
Should work exactly as for int.  (Note that gmpy2 allows more permissible syntax.)

**Comment by rruuaanng** [comment]
Give it to me, it is a simple string concatenation :)

**Comment by skirpichev** [comment]
Feel free to work on any issue.  But keep in mind, that it's *not* a simple string concatenation.

**Comment by rruuaanng** [comment]
Maybe I'm underestimating it. Allow me to observe the behavior of gmpy2 to decide its behavior. At least it seems to be a string concatenation in int.

**Comment by skirpichev** [comment]
We should match int's behavior.

**Comment by rruuaanng** [comment]
I have completed it, please let me prepare for the test.
```
>>> from gmp import mpz
>>> mpz('123_1231')
mpz(1231231)
>>> mpz('123_456_789')
mpz(123456789)
```
