### ISSUE TITLE
Support floats in mpz constructor

### ISSUE THREAD

**Issue by skirpichev** [diofant/python-gmp#75]

**Comment by rruuaanng** [comment]
Do you mean string mode or real number mode?
```
>>> int('14.2')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: invalid literal for int() with base 10: '14.2'
>>> int(14.2)
14
```

**Comment by skirpichev** [comment]
The mpz() constructor should work as int() constructor.  I.e., accept same input and reject same input.  Produced values should be equal (``mpz(<same_stuff>) == int(<same_stuff>)``).
